#!/usr/bin/env python3
"""
BEAR-HUB Launcher
=================

This script launches the BEAR-HUB Streamlit application.
It loads the configuration generated by the installer and starts Streamlit.
"""

import os
import sys
import subprocess
from streamlit.web import cli as stcli

def load_config():
    """Loads environment variables from .bear-hub.env"""
    # If frozen, we look for config in the user's home dir (same as installer)
    if getattr(sys, 'frozen', False):
        root_dir = os.path.join(os.path.expanduser("~"), "BEAR-HUB")
    else:
        root_dir = os.path.abspath(os.path.dirname(__file__))

    config_file = os.path.join(root_dir, ".bear-hub.env")

    if not os.path.exists(config_file):
        print(f"WARNING: Configuration file not found at {config_file}")
        print("Please run 'bear-installer' first.")
        # We don't exit, we try to run anyway, maybe env vars are already set manually
        return

    print(f"Loading configuration from {config_file}...")
    with open(config_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Format: export VAR="VALUE"
            if line.startswith("export "):
                line = line[7:]

            if "=" in line:
                key, value = line.split("=", 1)
                # Remove quotes if present
                if (value.startswith('"') and value.endswith('"')) or \
                   (value.startswith("'") and value.endswith("'")):
                    value = value[1:-1]

                os.environ[key] = value
                print(f"  {key}={value}")

def main():
    load_config()

    if getattr(sys, 'frozen', False):
        base_path = sys._MEIPASS
    else:
        base_path = os.path.dirname(os.path.abspath(__file__))

    app_path = os.path.join(base_path, "BEAR-HUB.py")

    if not os.path.exists(app_path):
        print(f"ERROR: Application file not found at {app_path}")
        sys.exit(1)

    print(f"Launching BEAR-HUB from {app_path}...")

    # Construct the argument list for streamlit
    # We mimic 'streamlit run BEAR-HUB.py'
    sys.argv = [
        "streamlit",
        "run",
        app_path,
        "--global.developmentMode=false",
        "--server.headless=true",  # Often good for executables
    ]

    sys.exit(stcli.main())

if __name__ == "__main__":
    main()
