#!/bin/bash
set -euo pipefail

# Script to clean up artifacts and docker images generated by the installer tests

echo "Cleaning up artifacts..."
if [ -d "artifacts" ]; then
    rm -rf artifacts
    echo "  - Removed artifacts/ directory."
else
    echo "  - No artifacts/ directory found."
fi

echo "Cleaning up Docker images..."
IMAGES=("bear-hub-test:ubuntu22" "bear-hub-test:debian12")

for img in "${IMAGES[@]}"; do
    if docker image inspect "$img" >/dev/null 2>&1; then
        docker rmi "$img"
        echo "  - Removed image: $img"
    else
        echo "  - Image not found (already removed?): $img"
    fi
done

echo "Cleanup complete."
